[[redirects]]
  from = "/it/*"
  to = "pages/it.html/:splat"
  status = 200

[[redirects]]
  from = "/en/*"
  to = "pages/en.html/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html/:splat"
  status = 200
